### PR TITLE
Added compatibility for Android Studio 4.1.

### PR DESCRIPTION
**Pull request by Yubyf**

### CODE REVIEW

**Review by AndyWing — APPROVED** [review]

**Comment by AndyWing** [comment]
Good job, thanks 👍

**Comment by AndyWing** [comment]
I have tested the version 3.4 and found no compatibility problems in AS4.1.
It seems that gradle compile plugin is compatible with AS4.1?
If so, we no need to restrict the 'since-build' to the '201.8743.12' to ensure downstream compat.

**Comment by Yubyf** [comment]
> I have tested the version 3.4 and found no compatibility problems in AS4.1.
> It seems that gradle compile plugin is compatible with AS4.1?
> If so, we no need to restrict the 'since-build' to the '201.8743.12' to ensure downstream compat.

Sorry, I just borrowed directly from the compatibility [implementation](https://github.com/YahiaAngelo/WIFIADB/commit/875f0cc09378bf19a16f1756b9eae0d0704b9b0e) from another developer but did not review. I think you can revert the `<idea-version since-build>` tag directly if you have checked it.

**Comment by AndyWing** [comment]
since-build was changed to 107.121 in the  commit 701526e7f88a12470a404360811287d88520e964

**Pull request merged**
